DefaultBundle_homepage:
  pattern:  /
  defaults: { _controller: DefaultBundle:Default:index }
DefaultBundle_static_page:
  pattern:  page/{slug}
  defaults: { _controller: DefaultBundle:Page:index }
  requirements:
    slug:  about|contacts|reglament-xcm-2014|information-xcm-2014|faq-xcm-2014|results-xcm-2014
DefaultBundle_payment_response:
  pattern:  payment/{slug}
  defaults: { _controller: DefaultBundle:Page:index }
  requirements:
    slug:  success|fail
